def: generator analyser

generator:
	g++ -I /home/rehrev/Documents/Yazilim/C++/eigen-eigen-b3f3d4950030 ../DataGenerator/main.cpp ../Agent.cpp ../Simulation.cpp ../Model.cpp ../LanguageDynamics.cpp -o DataGenerator

analyser:
	g++ -I /home/rehrev/Documents/Yazilim/C++/eigen-eigen-b3f3d4950030 ../DataAnalyser/main.cpp ../Agent.cpp ../Simulation.cpp ../Model.cpp ../LanguageDynamics.cpp -o DataAnalyser
